### ISSUE TITLE
Práctica 7 - Pruebas unitarias

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-nuggets-de-pollo#1]
[PRAC_7-PRUEBAS_UNITARIAS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-nuggets-de-pollo/files/15477449/PRAC_7-PRUEBAS_UNITARIAS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
